### ISSUE TITLE
Camera position locks while chatting

### ISSUE THREAD

**Issue by Tugimus** [IroncladGames/SinsOfADarkAge#251]
If you press Enter or Shift Enter to chat, the camera becomes locked to it's current position.  You cannot move it by clicking the mini map, using arrow keys, or even when the camera should be locked to your hero by Y it remains stuck in one spot.

Also, if you respawn with chat open, the camera does not reset to the fountain.

**Comment by writor** [comment]
Based on testing in the most recent build (42604), these issues no longer occur. Y locked cameras follow the hero while the player is typing. Edge scroll works while typing. The scroll keys even work while typing (though left and right arrows move the cursor in chat rather than the camera by default, so the controls will need to be rebound by players who want to do this).
