### ISSUE TITLE
Might Of The Empire - Vallamere

### ISSUE THREAD

**Issue by CrackerJax** [IroncladGames/SinsOfADarkAge#657]
Before the rework of Vallamere, when Might of The Empire was active, it would show your damage increase down on your stats(bottom left hand corner window)(iirc). It no longer does however.

May we see our damage increase again please?

**Comment by writor** [comment]
Since @Bulletsponge's post, Might of the Empire has been reworked again. It now grants Attack Speed, Armor, and Magic Resistance, as well as a shield. All of the stat boosts are reflected in the character window. :) Therefore, I'm closing this issue for now. If anyone thinks there may be a lingering question of whether/how bonus Attack Damage should be communicated to the player, please open a separate issue. (Bataar gains Attack Damage with his W, for example.) Thanks CJ!

**Comment by CrackerJax** [comment]
Thanks guys!
