### ISSUE TITLE
Rachne's Q targetting very inconsistent

### ISSUE THREAD

**Issue by Supified** [IroncladGames/SinsOfADarkAge#737]
When trying to hit an enemy hero with Rachne's q, it has a very high probablility of simply hitting the nearest minion instead, which puts her at a distinct disadvantage.  This even occurs when the hero is not next to a minion, making a misclick very unlikely the cause, so long as a minion is in the targetting circle and closer to you than the hero it seems to hit the minion instead.

**Comment by writor** [comment]
So, it sounds like this may have been an issue with accidentally smart casting. We made some changes in a recent patch (http://soada.wikia.com/wiki/41622) that should make this less likely. You can't set both normal and smart casting to the same key.

Also, it's kind of funny...LoL has adopted SoaDA terminology as of 3.12 (http://leagueoflegends.wikia.com/wiki/Quick_cast). 

My personal beef with Rachna's Q...it's way too easy to cancel, because of what feels like an excessively long animation/excessively short range, given the damage.

**Comment by Supified** [comment]
I think that was it, that I had it mapped to multiple keys and smart cast was taking over.  

My personal beef with her q is it's very uninspired looking.  Not meant to offend, but you do the cast and so far as I can tell it just happens.  No animation of her injecting them with something or what have you.  Could use a bit more special effects.

**Comment by writor** [comment]
Thanks Supe! I'll create a separate issue with your Rachna suggestions, and close this one for now. Happy New Year!
