### ISSUE TITLE
Cannot connect to servers - Got temp banned for it

### ISSUE THREAD

**Issue by ShadowMageAlpha** [IroncladGames/SinsOfADarkAge#978]
I've tried multiple times to use match-making to connect to games.
Every time I've gotten into a queue with people and accepted, only to apparently time-out on connecting to the server.  I'm currently waiting out a temp-ban to try again, but I have an idea of how that will go.

**Comment by ShadowMageAlpha** [comment]
Queue'd up again. Failed to connect.  Banned for 19 minutes.

**Comment by uncannymanny** [comment]
Hey ShadowMageAlpha.

Thanks for the report.

Sorry that happened. Next time something like this happens, could you press escape and send a bug report? It will attach a log file of your current session for the devs to look into.

Otherwise, it may be possible to find an older log file in which the issue happened and send that as well. It may require some work on your end though (finding a file and matching it up time wise.) If it's easier to wait to recreate, then you can do the in-game bug reporter route instead.

**Comment by jseward** [comment]
Hi ShadowMageAlpha. Is there any chance you may have a firewall or something preventing you from connecting to our game servers? What region are you connecting to?

**Comment by jseward** [comment]
I would like to figure out why you can't connect to the game servers and are getting wrongfully banned.

A few questions if you don't mind.

Are you able to connect to any game servers? For example can you try creating a custom game?

I looked through the logs and the game most recently failed to join was at 66.155.58.113

Can you try to ping this ip and paste your results?

1. run cmd.exe
2. ping 66.155.58.113

thanks for the help and sorry for the inconvenience.

**Comment by ShadowMageAlpha** [comment]
@uncannymanny I had already filed a bug report when I was banned previously for 8 minutes.

@jseward I am not behind any firewall.  I was attempting to connect to USEast and USWest.  
I was not able to connect to any game severs, but there weren't any custom games for me to try at the time.

For the ping-test, I sent 4 packets, received 4, lost 0.  Min ping was 98ms, max was 101ms, average was 99ms.

**Comment by ShadowMageAlpha** [comment]
The problem has been solved. Apparently it was my Anti-Virus being very stupid.

**Comment by jseward** [comment]
Thanks for the update. Let us know if you have any other problems.
